# Generated by Django 3.0.5 on 2020-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proServices', '0002_auto_20200520_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoeditingplans',
            name='type',
            field=models.CharField(choices=[('Single', 'Single Job'), ('Weekly', 'Weekly Plan'), ('Monthly', 'Monthly Plan')], max_length=18),
        ),
    ]
