# Generated by Django 3.0.5 on 2020-05-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proServices', '0004_auto_20200520_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEditingPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proServices.VideoEditingPlans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proServices.UserEditingPlans')),
            ],
        ),
    ]
