# Generated by Django 3.0.5 on 2020-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proServices', '0005_subscription_usereditingplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditingplans',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
