# Generated by Django 3.0.5 on 2020-05-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proServices', '0006_auto_20200520_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereditingplans',
            old_name='active',
            new_name='is_active',
        ),
    ]
