# Generated by Django 3.0.5 on 2020-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proServices', '0009_auto_20200524_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoeditingplans',
            name='type',
            field=models.CharField(choices=[('Single Job', 'Single Job'), ('Weekly Plan', 'Weekly Plan'), ('Monthly Plan', 'Monthly Plan')], max_length=18),
        ),
    ]
