# Generated by Django 3.0.5 on 2020-06-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proServices', '0010_auto_20200525_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoeditingplans',
            name='description',
        ),
    ]
