# Generated by Django 3.0.5 on 2020-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200430_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Music', 'Music Shows'), ('Studio', 'Studio'), ('Food', 'Food'), ('Weeding', 'Weeding'), ('Travel', 'Travel')], default='', max_length=10),
        ),
    ]
