# Generated by Django 3.0.5 on 2020-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_photo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('category', models.CharField(choices=[('institutional', 'Institutional film'), ('shows', 'Music Shows'), ('events', 'Events'), ('drone', 'Drone footage')], default='', max_length=20)),
                ('description', models.TextField()),
                ('videoUrl', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Music', 'Music Shows'), ('Studio', 'Studio'), ('Food', 'Food'), ('Weeding', 'Weeding'), ('Travel', 'Travel')], default='', max_length=20),
        ),
    ]
