# Generated by Django 3.0.5 on 2020-05-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200507_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('institutional', 'Institutional'), ('music', 'Music'), ('events', 'Events'), ('drone', 'Drone')], default='', max_length=20),
        ),
    ]
