# Generated by Django 3.0.5 on 2020-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200508_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Music', 'Music Shows'), ('Studio', 'Studio'), ('Food', 'Food'), ('Weeding', 'Weeding'), ('Travel', 'Travel'), ('drone', 'Drone'), ('fineArt', 'Fine Art')], default='', max_length=20),
        ),
    ]
