# Generated by Django 3.0.5 on 2020-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200512_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Music', 'Music Shows'), ('Studio', 'Studio'), ('Food', 'Food'), ('Weeding', 'Weeding'), ('Drone', 'Drone'), ('FineArt', 'Fine Art')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('institutional', 'Institutional'), ('videoMusic', 'Music'), ('events', 'Events'), ('drone', 'Drone')], default='', max_length=20),
        ),
    ]
